In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [28]:
df = pd.read_csv("Datasets/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [29]:
#Before we use the above data for anything, we need to pre-process it. for example, we need to replace the null value in bedrooms column with something
#we can take the median value from the list of bedrooms and use it to replace null
import math
median_bedroom = math.floor(df.bedrooms.median())

In [30]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)

In [31]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [32]:
#let us use the linear regression function
reg = linear_model.LinearRegression()

In [33]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [34]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [35]:
reg.intercept_

221323.00186540408

In [36]:
reg.predict([[3000,3,40]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [37]:
area = 3000
bedrooms = 3
age = 40
price = 112.06244194*area + 23388.88007794*bedrooms - 3231.71790863*age + 221323.00186540408
price

498408.2515740241

In [38]:
reg.predict([[2500,4,5]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [39]:
area = 2500
bedrooms = 4
age = 5
price = 112.06244194*area + 23388.88007794*bedrooms - 3231.71790863*age + 221323.00186540408
price

578876.0374840142